spring:
  application:
    name: eureka-client # 服务节点名称
server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: eureka-client-01
  client:
    service-url:
      defaultZone: http://eureka01:8761/eureka/  # 向Server发送注册信息，Eureka-Server的url，可以将Eureka-Server集群中的所有节点地址写进来
    healthcheck:
      enabled: true   # 检测已注册的服务的健康状态
# Actuator Setting
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:   # \actuator\info
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    source: @java.version@
    profile: ${spring.profiles}
---
# 节点2
spring:
  profiles: client-02 # 命令行参数
server:
  port: 8082
eureka:
  instance:
    hostname: eureka-client-02
---
# 节点3
spring:
  profiles: client-03 # 命令行参数
server:
  port: 8083
eureka:
  instance:
    hostname: eureka-client-03
---
# 节点4
spring:
  profiles: client-04 # 命令行参数
server:
  port: 8084
eureka:
  instance:
    hostname: eureka-client-04
---
# 节点5
spring:
  profiles: client-05 # 命令行参数
server:
  port: 8085
eureka:
  instance:
    hostname: eureka-client-05