server:
  port: 8889
spring:
  application:
    name: config-server-00
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TwinkleSevenStream/spring-cloud-config-demo/  # 配置文件的git远程目录
          search-paths: Configs # 读取配置文件的路径


