server:
  port: 8889
spring:
  application:
    name: config-server-00
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TwinkleSevenStream/SpringCloudMvnDemo/tree/master/config-server/src/main/resources/
          search-paths: Configs
      label: master


